# Generated by Django 5.2.3 on 2026-06-02 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre_familia', models.CharField(max_length=100, verbose_name='Nombre de la Familia/Grupo')),
                ('vivienda', models.CharField(max_length=50, verbose_name='Número o Tipo de Vivienda')),
                ('direccion', models.TextField(verbose_name='Dirección Completa')),
                ('catastro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código Catastral')),
                ('fecha_registro', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Familia',
                'verbose_name_plural': 'Familias',
                'db_table': 'familias',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ActaReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Acta')),
                ('fecha_reunion', models.DateTimeField(verbose_name='Fecha y Hora de la Reunión')),
                ('lugar', models.CharField(max_length=200, verbose_name='Lugar de la Reunión')),
                ('asistentes', models.TextField(verbose_name='Lista de Asistentes')),
                ('contenido', models.TextField(verbose_name='Contenido del Acta')),
                ('acuerdos', models.TextField(blank=True, verbose_name='Acuerdos Tomados')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='actas/', verbose_name='Archivo PDF')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Acta de Reunión',
                'verbose_name_plural': 'Actas de Reunión',
                'db_table': 'actas_reunion',
                'ordering': ['-fecha_reunion'],
            },
        ),
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre_censo', models.CharField(help_text='Nombre identificativo de la campaña de censo', max_length=200, verbose_name='Nombre del Censo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('descripcion', models.TextField(help_text='Descripción detallada del objetivo del censo', verbose_name='Descripción')),
                ('categoria_enfoque', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('vivienda', 'Vivienda'), ('desempleo', 'Desempleo'), ('nutricion', 'Nutrición'), ('seguridad', 'Seguridad'), ('servicios_publicos', 'Servicios Públicos'), ('poblacion', 'Censo Poblacional'), ('general', 'General')], default='general', max_length=50, verbose_name='Categoría de Enfoque')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='activo', max_length=20, verbose_name='Estatus del Censo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='censos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Censo',
                'verbose_name_plural': 'Censos',
                'db_table': 'censos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='EgresoComunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Egreso')),
                ('tipo_egreso', models.CharField(choices=[('mantenimiento', 'Mantenimiento Comunitario'), ('servicios', 'Servicios Públicos'), ('actividades', 'Actividades Comunitarias'), ('emergencias', 'Emergencias'), ('administrativos', 'Gastos Administrativos'), ('otros', 'Otros Egresos')], default='mantenimiento', max_length=50, verbose_name='Tipo de Egreso')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (Bs.)')),
                ('beneficiario', models.CharField(blank=True, max_length=200, verbose_name='Beneficiario')),
                ('soporte', models.FileField(blank=True, null=True, upload_to='soportes/egresos/', verbose_name='Soporte')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Egreso Comunal',
                'verbose_name_plural': 'Egresos Comunales',
                'db_table': 'egresos_comunales',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Habitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('es_jefe_familia', models.BooleanField(default=False, verbose_name='¿Es Jefe de Familia?')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('nivel_educativo', models.CharField(blank=True, choices=[('ninguno', 'Ninguno'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('tecnico', 'Técnico Medio'), ('universitario', 'Universitario'), ('postgrado', 'Postgrado')], max_length=50, verbose_name='Nivel Educativo')),
                ('ingresos_mensuales', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingresos Mensuales (Bs.)')),
                ('condiciones_salud', models.TextField(blank=True, verbose_name='Condiciones de Salud')),
                ('fecha_registro_comunitario', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitantes', to='myapp.familia', verbose_name='Familia / Hogar')),
            ],
            options={
                'verbose_name': 'Habitante',
                'verbose_name_plural': 'Habitantes',
                'db_table': 'habitantes',
                'ordering': ['familia', '-es_jefe_familia', 'apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConstanciaResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Generación')),
                ('fecha_documento', models.DateField(verbose_name='Fecha del Documento')),
                ('finalidad', models.TextField(verbose_name='Finalidad de la Constancia')),
                ('contenido', models.TextField(verbose_name='Contenido de la Constancia')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='constancias/', verbose_name='Archivo PDF')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constancias', to='myapp.habitante', verbose_name='Habitante Solicitante')),
            ],
            options={
                'verbose_name': 'Constancia de Residencia',
                'verbose_name_plural': 'Constancias de Residencia',
                'db_table': 'constancias_residencia',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Comité')),
                ('tipo_comite', models.CharField(choices=[('finanzas', 'Comité de Finanzas'), ('salud', 'Comité de Salud'), ('educacion', 'Comité de Educación'), ('vivienda', 'Comité de Vivienda'), ('deporte', 'Comité de Deporte y Recreación'), ('cultura', 'Comité de Cultura'), ('seguridad', 'Comité de Seguridad'), ('alimentacion', 'Comité de Alimentación'), ('medio_ambiente', 'Comité de Medio Ambiente'), ('otro', 'Otro Comité')], default='otro', max_length=50, verbose_name='Tipo de Comité')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Comité Activo')),
                ('vocero_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comites_dirigidos', to='myapp.habitante', verbose_name='Vocero Principal')),
            ],
            options={
                'verbose_name': 'Comité',
                'verbose_name_plural': 'Comités',
                'db_table': 'comites',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CensoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la participación del habitante', verbose_name='Observaciones')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_censo', to='myapp.censo', verbose_name='Censo')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_censo', to='myapp.habitante', verbose_name='Habitante')),
            ],
            options={
                'verbose_name': 'Participante de Censo',
                'verbose_name_plural': 'Participantes de Censo',
                'db_table': 'censo_participantes',
                'ordering': ['censo', 'fecha_registro', 'habitante__nombre'],
            },
        ),
        migrations.AddField(
            model_name='censo',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='censos_participados', through='myapp.CensoParticipante', to='myapp.habitante', verbose_name='Participantes'),
        ),
        migrations.CreateModel(
            name='IngresoComunal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Ingreso')),
                ('tipo_ingreso', models.CharField(choices=[('aportes', 'Aportes de Familias'), ('donaciones', 'Donaciones'), ('actividades', 'Actividades Comunitarias'), ('subvenciones', 'Subvenciones'), ('otros', 'Otros Ingresos')], default='aportes', max_length=50, verbose_name='Tipo de Ingreso')),
                ('concepto', models.CharField(max_length=200, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto (Bs.)')),
                ('soporte_digital', models.FileField(blank=True, null=True, upload_to='soportes/ingresos/', verbose_name='Soporte Digital')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Ingreso Comunal',
                'verbose_name_plural': 'Ingresos Comunales',
                'db_table': 'ingresos_comunales',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('descripcion', models.TextField(verbose_name='Descripción del Proyecto')),
                ('monto_estimado', models.DecimalField(decimal_places=2, help_text='Monto estimado en bolívares', max_digits=12, verbose_name='Monto Estimado (Bs.)')),
                ('estatus', models.CharField(choices=[('planificacion', 'Planificación'), ('ejecucion', 'Ejecución'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20, verbose_name='Estatus del Proyecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='myapp.comite', verbose_name='Comité Responsable')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('coordinador', 'Coordinador'), ('ejecutor', 'Ejecutor'), ('contralor', 'Contralor'), ('colaborador', 'Colaborador'), ('beneficiario', 'Beneficiario')], default='colaborador', max_length=20, verbose_name='Rol en el Proyecto')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados', to='myapp.habitante', verbose_name='Habitante')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='myapp.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Integrante de Proyecto',
                'verbose_name_plural': 'Integrantes de Proyecto',
                'db_table': 'proyecto_integrantes',
                'ordering': ['proyecto', 'rol', 'habitante__nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='habitante',
            constraint=models.UniqueConstraint(condition=models.Q(('es_jefe_familia', True), ('is_deleted', False)), fields=('familia',), name='unique_jefe_activo_por_familia'),
        ),
        migrations.AddConstraint(
            model_name='habitante',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cedula',), name='unique_cedula_habitante_activo'),
        ),
        migrations.AlterUniqueTogether(
            name='censoparticipante',
            unique_together={('censo', 'habitante')},
        ),
        migrations.AlterUniqueTogether(
            name='proyectointegrante',
            unique_together={('proyecto', 'habitante')},
        ),
    ]
