# Generated by Django 5.2.3 on 2026-06-02
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        # Solo crear las tablas que faltan
        # Las tablas ya creadas en 0001_initial se omitirán automáticamente
    ]