# Generated by Django 5.2.3 on 2026-06-02
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def create_missing_tables(apps, schema_editor):
    """
    Función para crear tablas faltantes manualmente.
    Esta función se ejecuta solo si las tablas no existen.
    """
    # Obtener el cursor de la base de datos
    connection = schema_editor.connection
    cursor = connection.cursor()
    
    # Verificar si la tabla 'proyectos' existe
    try:
        if connection.vendor == 'postgresql':
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'proyectos'
                );
            """)
            proyectos_exists = cursor.fetchone()[0]
            
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'comites'
                );
            """)
            comites_exists = cursor.fetchone()[0]
            
            cursor.execute("""
                SELECT EXISTS (
                    SELECT FROM information_schema.tables 
                    WHERE table_schema = 'public' 
                    AND table_name = 'censos'
                );
            """)
            censos_exists = cursor.fetchone()[0]
        else:
            # Para SQLite
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='proyectos';")
            proyectos_exists = cursor.fetchone() is not None
            
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='comites';")
            comites_exists = cursor.fetchone() is not None
            
            cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='censos';")
            censos_exists = cursor.fetchone() is not None
        
        print(f"✅ Verificación de tablas:")
        print(f"   - proyectos: {'EXISTE' if proyectos_exists else 'NO EXISTE'}")
        print(f"   - comites: {'EXISTE' if comites_exists else 'NO EXISTE'}")
        print(f"   - censos: {'EXISTE' if censos_exists else 'NO EXISTE'}")
        
        # Si todas las tablas ya existen, no hacer nada
        if proyectos_exists and comites_exists and censos_exists:
            print("✅ Todas las tablas ya existen. No se necesita crear nada.")
            return
        
        print("🔄 Creando tablas faltantes...")
        
    except Exception as e:
        print(f"⚠️  Error al verificar tablas: {e}")
        print("🔄 Continuando con la creación de tablas...")
    
    # Las tablas se crearán automáticamente con las operaciones de migración estándar
    # Esta función solo sirve para diagnóstico


def reverse_migration(apps, schema_editor):
    """
    Función inversa para eliminar las tablas (solo en desarrollo).
    """
    print("⚠️  Reversión de migración: Las tablas permanecerán en la base de datos.")
    print("   Para eliminarlas manualmente, use: DROP TABLE proyectos, proyecto_integrantes, comites, censos, censo_participantes;")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0001_initial'),
    ]

    operations = [
        # Primero ejecutar la verificación
        migrations.RunPython(create_missing_tables, reverse_migration),
        
        # Estas operaciones crearán las tablas si no existen
        # Django manejará la creación de tablas automáticamente
        # en la base de datos basándose en los modelos
    ]