# Generated by Django 5.2.3 on 2026-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='habitante',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('cedula',), name='unique_cedula_habitante_activo'),
        ),
    ]
