# Generated by Django 5.2.3 on 2026-06-03 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_create_missing_tables'),
        ('myapp', '0002_fix_missing_tables'),
    ]

    operations = [
    ]
