# Generated by Django 5.2.3 on 2026-06-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_merge_20260602_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitante',
            name='tipo_cedula',
            field=models.CharField(choices=[('V', 'Venezolano/a'), ('E', 'Extranjero/a')], default='V', max_length=1),
        ),
    ]
