# Generated by Django 5.2.3 on 2026-06-15 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_habitante_tipo_cedula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteDemografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_reporte', models.CharField(max_length=150, verbose_name='Título del Reporte')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('filtro_genero', models.CharField(choices=[('TODOS', 'Todos'), ('M', 'Masculino'), ('F', 'Femenino')], default='TODOS', max_length=5, verbose_name='Filtro de Género')),
                ('filtro_edad', models.CharField(choices=[('TODOS', 'Todas las edades'), ('MENOR_12', 'Niños (Menores a 12 años)'), ('MENOR_16', 'Adolescentes (Menores a 16 años)'), ('TERCERA_EDAD', 'Adultos Mayores / 3ra Edad (>= 60 años)')], default='TODOS', max_length=15, verbose_name='Segmentación por Edad')),
                ('incluir_datos_familia', models.BooleanField(default=True, verbose_name='Desglosar por Grupo Familiar')),
                ('formato_salida', models.CharField(choices=[('PDF', 'Documento PDF (.pdf)'), ('EXCEL', 'Hoja de Cálculo (.xlsx)'), ('AMBOS', 'Ambos Formatos')], default='AMBOS', max_length=10, verbose_name='Formato Solicitado')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes/pdfs/', verbose_name='Archivo PDF')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='reportes/excels/', verbose_name='Archivo Excel')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Generado por')),
            ],
            options={
                'verbose_name': 'Reporte Demográfico',
                'verbose_name_plural': 'Reportes Demográficos',
                'db_table': 'cc_reportes_demograficos',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
