# Generated by Django 5.2.3 on 2026-06-20 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_reportedemografico'),
    ]

    operations = [
        migrations.AddField(
            model_name='actareunion',
            name='cuenta_bancaria',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Cuenta Bancaria Comunal'),
        ),
    ]
