# Generated by Django 5.2.3 on 2026-06-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_actareunion_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actareunion',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cuenta Bancaria Comunal'),
        ),
    ]
