# Generated by Django 5.2.3 on 2026-07-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_actareunion_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='constanciaresidencia',
            name='tipo_tramite',
            field=models.CharField(choices=[('RESIDENCIA', 'Constancia de Residencia'), ('BUENA_CONDUCTA', 'Constancia de Buena Conducta'), ('POST_MORTEM', 'Constancia Post-Mortem / Fallecimiento')], default='RESIDENCIA', max_length=20, verbose_name='Tipo de Trámite'),
        ),
    ]
