# Generated by Django 5.2.3 on 2026-07-19 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_constanciaresidencia_tipo_tramite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 👇 1. PRIMERO eliminamos la restricción única para que use el campo 'censo' mientras exista
        migrations.AlterUniqueTogether(
            name='censoparticipante',
            unique_together=None,
        ),
        # 👇 2. SEGUNDO removemos el campo físicamente de la estructura
        migrations.RemoveField(
            model_name='censoparticipante',
            name='censo',
        ),
        migrations.RemoveField(
            model_name='censoparticipante',
            name='habitante',
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('nombre_actividad', models.CharField(help_text='Nombre identificativo de la campaña de actividad', max_length=200, verbose_name='Nombre de la actividad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('descripcion', models.TextField(help_text='Descripción detallada del objetivo del actividad', verbose_name='Descripción')),
                ('categoria_enfoque', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('vivienda', 'Vivienda'), ('desempleo', 'Desempleo'), ('nutricion', 'Nutrición'), ('seguridad', 'Seguridad'), ('servicios_publicos', 'Servicios Públicos'), ('poblacion', 'Censo Poblacional'), ('general', 'General')], default='general', max_length=50, verbose_name='Categoría de Enfoque')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='activo', max_length=20, verbose_name='Estatus de la actividad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividad',
                'db_table': 'actividad',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ActividadParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la participación del habitante', verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_actividad', to='myapp.actividad', verbose_name='Actividad')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_actividad', to='myapp.habitante', verbose_name='Habitante')),
            ],
            options={
                'verbose_name': 'Participante de Actividad',
                'verbose_name_plural': 'Participantes de Actividad',
                'db_table': 'actividad_participantes',
                'ordering': ['actividad', 'fecha_registro', 'habitante__nombre'],
                'unique_together': {('actividad', 'habitante')},
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='actividad_participados', through='myapp.ActividadParticipante', to='myapp.habitante', verbose_name='Participantes'),
        ),
        migrations.DeleteModel(
            name='Censo',
        ),
        migrations.DeleteModel(
            name='CensoParticipante',
        ),
    ]
