# Generated by Django 5.2.3 on 2026-05-18 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_actareunion_egresocomunal_familia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Comité')),
                ('tipo_comite', models.CharField(choices=[('finanzas', 'Comité de Finanzas'), ('salud', 'Comité de Salud'), ('educacion', 'Comité de Educación'), ('vivienda', 'Comité de Vivienda'), ('deporte', 'Comité de Deporte y Recreación'), ('cultura', 'Comité de Cultura'), ('seguridad', 'Comité de Seguridad'), ('alimentacion', 'Comité de Alimentación'), ('medio_ambiente', 'Comité de Medio Ambiente'), ('otro', 'Otro Comité')], default='otro', max_length=50, verbose_name='Tipo de Comité')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.BooleanField(default=True, verbose_name='Comité Activo')),
                ('vocero_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comites_dirigidos', to='myapp.person', verbose_name='Vocero Principal')),
            ],
            options={
                'verbose_name': 'Comité',
                'verbose_name_plural': 'Comités',
                'db_table': 'comites',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin Estimada')),
                ('descripcion', models.TextField(verbose_name='Descripción del Proyecto')),
                ('monto_estimado', models.DecimalField(decimal_places=2, help_text='Monto estimado en bolívares', max_digits=12, verbose_name='Monto Estimado (Bs.)')),
                ('estatus', models.CharField(choices=[('planificacion', 'Planificación'), ('ejecucion', 'Ejecución'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='planificacion', max_length=20, verbose_name='Estatus del Proyecto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('comite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='myapp.comite', verbose_name='Comité Responsable')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proyectos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'db_table': 'proyectos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ProyectoIntegrante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('coordinador', 'Coordinador'), ('ejecutor', 'Ejecutor'), ('contralor', 'Contralor'), ('colaborador', 'Colaborador'), ('beneficiario', 'Beneficiario')], default='colaborador', max_length=20, verbose_name='Rol en el Proyecto')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_asignados', to='myapp.habitante', verbose_name='Habitante')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrantes', to='myapp.proyecto', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Integrante de Proyecto',
                'verbose_name_plural': 'Integrantes de Proyecto',
                'db_table': 'proyecto_integrantes',
                'ordering': ['proyecto', 'rol', 'habitante__persona__name'],
                'unique_together': {('proyecto', 'habitante')},
            },
        ),
    ]
