# Generated by Django 5.2.3 on 2026-05-26 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_add_proyectos_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('deleted_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Fecha de eliminación')),
                ('nombre_censo', models.CharField(help_text='Nombre identificativo de la campaña de censo', max_length=200, verbose_name='Nombre del Censo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('descripcion', models.TextField(help_text='Descripción detallada del objetivo del censo', verbose_name='Descripción')),
                ('categoria_enfoque', models.CharField(choices=[('salud', 'Salud'), ('educacion', 'Educación'), ('vivienda', 'Vivienda'), ('desempleo', 'Desempleo'), ('nutricion', 'Nutrición'), ('seguridad', 'Seguridad'), ('servicios_publicos', 'Servicios Públicos'), ('poblacion', 'Censo Poblacional'), ('general', 'General')], default='general', max_length=50, verbose_name='Categoría de Enfoque')),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado'), ('archivado', 'Archivado')], default='activo', max_length=20, verbose_name='Estatus del Censo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='censos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Censo',
                'verbose_name_plural': 'Censos',
                'db_table': 'censos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CensoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre la participación del habitante', verbose_name='Observaciones')),
                ('censo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes_censo', to='myapp.censo', verbose_name='Censo')),
                ('habitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_censo', to='myapp.habitante', verbose_name='Habitante')),
            ],
            options={
                'verbose_name': 'Participante de Censo',
                'verbose_name_plural': 'Participantes de Censo',
                'db_table': 'censo_participantes',
                'ordering': ['censo', 'fecha_registro', 'habitante__persona__name'],
                'unique_together': {('censo', 'habitante')},
            },
        ),
        migrations.AddField(
            model_name='censo',
            name='participantes',
            field=models.ManyToManyField(blank=True, related_name='censos_participados', through='myapp.CensoParticipante', to='myapp.habitante', verbose_name='Participantes'),
        ),
    ]
